config/routes.rb
Rails.application.routes.draw do

  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
  post "/graphql", to: "graphql#execute"
  get 'mechanics/create'
  get 'games/create'
  get 'games/update'
  get 'games/destroy'
  get 'games/details'
  get 'sessions/new'
  root 'static_pages#home'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post 'login', to: 'sessions#create', as: 'signin'
  delete 'logout', to: 'sessions#destroy'
  post '/games', to: 'games#create'
  delete '/games', to: 'games#destroy'
  post '/categories', to: 'categories#create'
  post '/mechanics', to: 'mechanics#create'
  resources :users, param: :username do
    resources :games, only: [:index, :create, :edit, :update, :destroy]
    resources :friendships, only: [:index]
  end
  resources :password_resets, only: [:new, :create, :edit, :update]
  resources :account_activations, only: [:edit]
  resources :categories, only: [:create]
  resources :mechanics, only: [:create]

  namespace :api do
    namespace :v1 do
     resources :games, only: [:index]
     resources :users, only: [:index, :destroy]
     resources :friendships, only: [:create, :destroy]
    end
  end

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-sm navbar-dark bg-dark navbar-fixed-top navbar-inverse">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "Game Shelf", root_path, class: "navbar-brand" %>
    <ul class="navbar-nav mr-auto">
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to "Games", user_games_url(current_user.username), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friends", user_friendships_url(current_user.username), class: "nav-link" %>
        </li>
      <% end %>
    </ul>
    <ul class="navbar-nav">
      <% if logged_in? %> 
        <li class="dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Profile", user_path(current_user.username), class: "dropdown-item" %>
                <div class="dropdown-divider"></div>
                <%= link_to "Log out", logout_path, method: :delete, class: "dropdown-item"%>
            </div>
          </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", signup_path, class: "nav-link" %>
        </li>
      <span class="navbar-text">|</span>
        <li class="nav-item">
          <%= link_to "Login", login_path, class: "nav-link" %>
        </li> 
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Game Shelf</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= vite_client_tag %>
    <%= vite_react_refresh_tag %>
    <%= vite_javascript_tag 'application' %>
    <script data-ad-client="ca-pub-7963882924406766" async src="https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <%= Sentry.get_trace_propagation_meta.html_safe %>

  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do | message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>